on:
  schedule:
    # Runs at 11:00 PM UTC every day
    - cron: '0 23 * * *'
  workflow_dispatch: # on button click

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'Drunken-Dragon'
        git config --global user.email '23655532+Drunken-Dragon@users.noreply.github.com'
        git config merge.ours.driver true

    - name: Sync Repository
      run: |
        git remote add upstream https://github.com/Azure/Azure-Sentinel.git
        git fetch upstream master
        git checkout master
        git rebase -X theirs upstream/master
        git push origin master --force
